import { products, categories } from './data.js';
import { getCart, cartItemCount, cartTotal } from './store.js';

const money = value => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
const productCard = product => `<article class="product-card"><a class="product-link" href="#/product/${product.id}"><span class="product-image"><img src="${product.image}" alt="${product.name}"></span><h3>${product.name}</h3><p>${product.category}</p><p class="price">${money(product.price)}</p></a><button class="quick-add" data-action="add" data-id="${product.id}" type="button" aria-label="Add ${product.name} to bag">+</button></article>`;
const productGrid = list => `<div class="product-grid">${list.map(productCard).join('')}</div>`;
export function updateCartCount() { const count = cartItemCount(); const element = document.querySelector('#cart-count'); element.textContent = count; element.setAttribute('aria-label', `${count} ${count === 1 ? 'item' : 'items'}`); }
export function homePage() { return `<section class="hero"><div class="hero-copy"><p class="eyebrow">New collection · Autumn 2026</p><h1>Objects for everyday light.</h1><p>Thoughtful essentials shaped to make ordinary rituals feel a little more intentional.</p><a class="button" href="#/shop">Shop the collection</a></div><div class="hero-image"><img src="assets/aurora.svg" alt="Amber Aurora Lamp"></div></section><section class="section container"><div class="section-heading"><div><p class="eyebrow">A slower home</p><h2>Made for the moments between.</h2></div><p>Small-batch objects in lasting materials, designed for the way a real home changes through the day.</p></div>${productGrid(products.slice(0, 4))}</section>`; }
export function shopPage(category) { const selected = categories.includes(category) ? category : 'All'; const filtered = selected === 'All' ? products : products.filter(product => product.category === selected); const filters = categories.map(item => `<a class="${item === selected ? 'active' : ''}" href="#/shop?category=${encodeURIComponent(item)}">${item}</a>`).join(''); return `<section class="container"><header class="shop-header"><div><p class="eyebrow">The collection</p><h1>Shop all</h1></div><nav class="filters" aria-label="Product categories">${filters}</nav></header><div class="shop-grid">${productGrid(filtered)}</div></section>`; }
export function productPage(id) { const product = products.find(item => item.id === id); if (!product) return notFoundPage(); return `<section class="container product-detail"><div class="product-detail-image"><img src="${product.image}" alt="${product.name}"></div><div class="product-detail-copy"><p class="eyebrow">${product.category}</p><h1>${product.name}</h1><p class="price">${money(product.price)}</p><p>${product.description}</p><button class="button" data-action="add" data-id="${product.id}" type="button">Add to bag</button></div></section>`; }
export function cartPage() { const cart = getCart(); if (!cart.length) return `<section class="container cart-layout"><div><p class="eyebrow">Your bag</p><h1>Nothing here yet.</h1><p>Find an object you’ll want to keep close.</p><a class="button" href="#/shop">Browse the shop</a></div></section>`; const items = cart.map(item => { const product = products.find(product => product.id === item.id); return `<article class="cart-item"><img src="${product.image}" alt=""><div><h2>${product.name}</h2><p>${money(product.price)}</p><div class="quantity-control" aria-label="Quantity for ${product.name}"><button data-action="quantity" data-id="${item.id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button data-action="quantity" data-id="${item.id}" data-delta="1" aria-label="Increase quantity">+</button></div></div><button class="remove" data-action="remove" data-id="${item.id}" type="button">Remove</button></article>`; }).join(''); return `<section class="container cart-layout"><div><p class="eyebrow">Your bag</p><h1>Almost yours.</h1><div class="cart-items">${items}</div></div><aside class="summary"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><strong>${money(cartTotal(products))}</strong></div><div class="summary-row"><span>Shipping</span><span>Calculated at checkout</span></div><div class="summary-row total"><span>Total</span><strong>${money(cartTotal(products))}</strong></div><button class="button" data-action="checkout" type="button">Continue to checkout</button></aside></section>`; }
export function aboutPage() { return `<section class="container about"><div><p class="eyebrow">About Lumina</p><h1>Less, but warmer.</h1></div><div><p>We make unhurried objects for rituals worth keeping: switching on a lamp at dusk, setting down a cup, gathering a favorite throw.</p><p>Every Lumina piece is designed to age quietly, use better, and earn its place at home.</p><a class="button secondary" href="#/shop">Explore the collection</a></div></section>`; }
export function notFoundPage() { return `<section class="container about"><div><p class="eyebrow">404</p><h1>This page wandered off.</h1></div><div><p>Let’s take you back to something beautiful.</p><a class="button" href="#/">Return home</a></div></section>`; }
